In [15]:
import numpy as np
import pandas as pd
import unittest

'''
Goal of this notebook is to showcase how to
take an arbitrary algorithm, implement it from
pseudo code and then modify it to fit your needs.
'''

## Pseudocode from Wikipedia
source = https://en.wikipedia.org/wiki/Quicksort
```
algorithm quicksort(A, lo, hi) is
    if lo < hi then
        p := partition(A, lo, hi)
        quicksort(A, lo, p - 1)
        quicksort(A, p + 1, hi)

algorithm partition(A, lo, hi) is
    pivot := A[hi]
    i := lo
    for j := lo to hi do
        if A[j] < pivot then
            swap A[i] with A[j]
            i := i + 1
    swap A[i] with A[hi]
    return i
```

In [52]:
# Wrapper function for ease of calling
# row = axis:0
# col = axis:1
def quick_sort(matrix, axis, selected_index):
    if axis == 1:
        #transpose the matrix
        matrix = matrix.transpose()
    
    quick_sort_recursive(matrix, selected_index, 0,len(matrix)-1)
    
    if axis == 1:
        matrix = matrix.transpose()
    return matrix

# Recursive quick_sort function that work on row
def quick_sort_recursive(matrix, selected_index, low_index, high_index):
    if low_index < high_index:
        pivot_index = partition(matrix, selected_index, low_index, high_index)
        quick_sort_recursive(matrix, selected_index, low_index, pivot_index - 1)
        quick_sort_recursive(matrix, selected_index, pivot_index + 1, high_index)

# where the magic happen
def partition(matrix, selected_index, low_index, high_index):
    def swap(matrix,i,j):
        temp = np.copy(matrix[:, i])
        matrix[:,i] = matrix[:,j]
        matrix[:,j] = temp
        
    pivot = matrix[selected_index, high_index]
    i = low_index
    for j in range(low_index, high_index+1):
        if matrix[selected_index, j] < pivot:
            swap(matrix,i,j)
            i = i + 1
    swap(matrix,i,high_index)
    return i

random_matrix = np.random.rand(5,5)
print("BEFORE SORTING: ")
print(random_matrix)
print("AFTER SORTING")
quick_sort(random_matrix,1,0)

BEFORE SORTING: 
[[0.23466178 0.6492908  0.67021173 0.46716194 0.23721482]
 [0.3052424  0.85301372 0.02447109 0.50954558 0.01903508]
 [0.21072777 0.278495   0.49687061 0.06586773 0.04866308]
 [0.54102282 0.40509217 0.78770998 0.70746844 0.72607101]
 [0.3897865  0.29465997 0.95588274 0.33847857 0.95158545]]
AFTER SORTING


array([[0.21072777, 0.278495  , 0.49687061, 0.06586773, 0.04866308],
       [0.23466178, 0.6492908 , 0.67021173, 0.46716194, 0.23721482],
       [0.3052424 , 0.85301372, 0.02447109, 0.50954558, 0.01903508],
       [0.3897865 , 0.29465997, 0.95588274, 0.33847857, 0.95158545],
       [0.54102282, 0.40509217, 0.78770998, 0.70746844, 0.72607101]])